### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by appi147** [hiteshnayak305/crawler-express#2]
I would like to make a basic search bar UI, how could I do that(where to get data in your code)

**Comment by hiteshnayak305** [comment]
From API you will get data in JSON formate. You can manipulate and display recieved information in your UI.

**Comment by appi147** [comment]
Is there any way that I create UI by forking it?

**Comment by hiteshnayak305** [comment]
no you dont need to fork it
just create normal webpages and use java script to request json data from api.

**Comment by appi147** [comment]
When I use JS it returns something related to cors

**Comment by hiteshnayak305** [comment]
var myInit = { method: 'GET',
               headers: myHeaders,
               mode: 'cors',
               cache: 'default' };


fetch('flowers.jpg', myInit).then(funct.................


Try this to change request method to access cross origin resources in <script></script> @appi147

**Comment by hiteshnayak305** [comment]
resolved. added cors headers.
